### ISSUE TITLE
Breaking 

### ISSUE THREAD

**Issue by Gwezieman** [SirCodalot/GrimReaper-Support#17]
**Describe the bug**
Works correctly when I first start up the server but after someone dies breaks the plugin altogether for the most part. I delete a plugin that I thought was the issue but didn't seem to be the case, have no clue what else it could be. (Disclaimer If we can stick this to DM's because I don't feel like sharing anything on my Server on github sorry. ( I.E ScreenShots, plugins etc..)  

**Error**
Gives me no error in console. Just breaks the plugin. Weird I know.

**To Reproduce**
I have no clue because can't seem to find the issue wrong with it. Doesn't tell me anything in console. 

**Expected behavior**
I designed all the files didn't work, Downloaded the default files again
Didn't work either, best bet is something to do with another plugin. but I could
be wrong. 

**Screenshots**
As stated above I would love to just on Discord if that's okay with you. (Gwezieman#5893)

**Server (Bukkit/Spigot/PaperSpigot) and Minecraft Version**
1.8.9 version

**Additional context**
N/A

**Comment by SirCodalot** [comment]
Yikes. I'll send you a friend request on discord.
